/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *   custom_emi.c
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *   This Module defines the EMI (external memory interface) related setting.
 *
 * Author:
 * -------
 *  EMI auto generator V0.01
 *
 *   Memory Device database last modified on 2013/5/4
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision$
 * $Modtime$
 * $Log$
 *
 *------------------------------------------------------------------------------
 * WARNING!!!  WARNING!!!   WARNING!!!  WARNING!!!  WARNING!!!  WARNING!!! 
 * This file is generated by EMI Auto-gen Tool.
 * Please do not modify the content directly!
 * It could be overwritten!
 *============================================================================
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#include "mt_emi.h"

#define NUM_EMI_RECORD (3)

int num_of_emi_records = NUM_EMI_RECORD;

EMI_SETTINGS emi_settings[] =
{
{
        0x0101,            //MCP(NAND+DDR1)
	{0xAD, 0xBC, 0x90, 0x55, 0x54},       //HYNIX
        0x0002202E,        //CONA
        0x88008800,        //DRVCTL0
        0x88008800,        //DRVCTL1
        0x00000005,        //DLE
        0x22824154,        //ACTIM
        0x00000000,        //GDDR3CTL
        0xF0040560,        //CONF1
        0x8283405C,        //DDR2CTL
        0x9F068CA0,        //TEST2_3
        0x00403361,        //CONF2
        0x11642842,        //PD_CTRL
        0x00000000,        //PADCTL3
        0x00000000,        //DQODLY
        0x00000000,        //ADDRODLY
        0x00000000,        //CLKODLY
        .reserved = {[0 ... 9] = 0},
        0x00000032,        //MODE_REG
        0x00000020,        //EXT_MODE_REG
    },
{
        0x0101,            //MCP(NAND+DDR1)
        {0x2C, 0xBC, 0x90, 0x55, 0x56},      //MICRON
        0x0002202E,        //CONA
        0x88008800,        //DRVCTL0
        0x88008800,        //DRVCTL1
        0x00000005,        //DLE
        0x22824154,        //ACTIM
        0x00000000,        //GDDR3CTL
        0xF0040560,        //CONF1
        0x8283405C,        //DDR2CTL
        0x9F008CA0,        //TEST2_3
        0x00403361,        //CONF2
        0x11642842,        //PD_CTRL
        0x00000000,        //PADCTL3
        0x00000000,        //DQODLY
        0x00000000,        //ADDRODLY
        0x00000000,        //CLKODLY
        .reserved = {[0 ... 9] = 0},
        0x00000032,        //MODE_REG
        0x00000020,        //EXT_MODE_REG
    },
{
        0x0101,            //MCP(NAND+DDR1)
        {0xEC, 0xBC, 0x00, 0x66, 0x56},          //SAMSUNG
        0x0002202E,        //CONA
        0x88008800,        //DRVCTL0
        0x88008800,        //DRVCTL1
        0x00000005,        //DLE
        0x22824165,        //ACTIM
        0x00000000,        //GDDR3CTL
        0xF00405A0,        //CONF1
        0x8283405C,        //DDR2CTL
        0x9F048CA0,        //TEST2_3
        0x00403361,        //CONF2
        0x11642842,        //PD_CTRL
        0x00000000,        //PADCTL3
        0x00000000,        //DQODLY
        0x00000000,        //ADDRODLY
        0x00000000,        //CLKODLY
        .reserved = {[0 ... 9] = 0},
        0x00000032,        //MODE_REG
        0x00000020,        //EXT_MODE_REG
    },
};

