/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Feb 28 20:30:26 2015
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1


#define CUST_EINT_MD1_CNT      0


