/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Feb 28 20:30:26 2015
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_BPI     GPIO_VIO18
#define GPIO_DVDD28_BSI     GPIO_VIO18
#define GPIO_DVDD28_NML2     GPIO_VIO18
#define MSDC_POWER_MC1     MSDC_VMC
#define MSDC_POWER_MC2     MSDC_VIO18_MC2
#define MUSB_POWER_PORT1     MUSB_VUSB33


