/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Sat Feb 28 20:30:26 2015
 * Do Not Modify the File.
 */



#include <mach/upmu_sw.h>


//****for customer use*******// 


//PMIC default enable/disable result

//PMIC mode select 
typedef enum
{
   BY_ENABLE = 0,
   BY_SRCLKEN = 1
}MODE_sel_enum;

////For Common use 

//For PMIC driver use




